version: 7.1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
skip_branch_with_pr: true
image: Visual Studio 2017
configuration:
- Release
- Debug
build:
  project: DolphinVM.sln
  verbosity: minimal
for:
-
  matrix:
    only:
      - configuration: Release
  test_script:
  - cmd: AppVeyorTestDolphinVM
artifacts:
- path: Dolphin\dpro.*
  name: DPro
- path: Release
  name: Release
deploy: off
notifications:
- provider: Email
  to:
  - bower@object-arts.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false