@echo off
rem -- Get git tag and commit information for use in product version

rem -- some projects are in the root directory and some are in a subdirectory
if not exist getVersion.cmd (
	cd ..
)

rem -- this seems to be the way to get the result of a command into a variable
for /f %%i in ('git describe --tag') do set GIT_TAG=%%i

rem -- generate Version.h

echo // this file generated by getVersion.cmd on %date% at %time% > Version.h
echo #if defined(_DEBUG) >> Version.h
echo #define GIT_TAG "%GIT_TAG% (Debug)" >> Version.h
echo #else >> Version.h
echo #define GIT_TAG "%GIT_TAG%" >> Version.h
echo #endif >> Version.h